### ISSUE TITLE
Black screen on fullscreen video playback (XZ3 dual, H9436)

### ISSUE THREAD

**Issue by SimenCodes** [Miustone/MARS_SOM#2]
_Hi!_

_Just installed this SOM on my XZ3. Except for this bug, everything runs smoothly, impressive work! Haven't really been tinkering with Xperia phones before, so I'm a bit lost here. Any idea what could be causing this?_

**Describe the Bug**
When I try to play a video in fullscreen, the screen flickers for half a second and then goes completely black. Audio keeps playing as normal.

Logcat: [video.log](https://github.com/Miustone/MARS_SOM/files/5761766/video.log)

Some observations:
* The bug consistenly happens moments after the onscreen controls disappear.
* Performing any action that brings back the playback controls also brings back the video.
* Playing the same video in the same app with onscreen controls visible does not trigger the bug.
* Videos that don't fill the screen (landscape video in portrait mode for example) does not trigger the bug.
* Behaviour is consistent across different video apps (Getting the bug in YouTube, Sony's Album app, Google Photos).
* Issue goes away when disabling MARS_SOM in Magisk and rebooting.

**Reproduce the Bug**
Steps to reproduce the Behavior:
1. Install the stock firmware from Sony (I used [this](https://forum.xda-developers.com/t/tool-newflasher-xperia-command-line-flasher.3619426/) newflasher).
1. Follow instructions in the [README](https://github.com/Miustone/MARS_SOM) to install MARS_SOM.
2. Record a minute or so of video using the camera app, or otherwise obtain a video. I used the demo video that ships with my device (Spiderverse trailer).
3. Play the video in Google Photos or similar app and make sure you enter fullscreen mode.
4. Wait for onscreen controls to go away.
5. Screen flickers and goes black.

**Without the Bug**
Video plays even when onscreen controls are gone.

**Smartphone (please complete the following Information):**
 - Device: Sony XZ3 dual-SIM (H9436)
 - OS: H9436_Customized UK_52.1.A.3.92-R6C
 - Version  V201220

**Additional Context**
Possibly related: after installing MARAS_SOM, the Smooth Display package started crashlooping because it can't find `android.view.DisplayEventReceiver`. As a workaround, I disabled the package and rebooted to make the crash dialogs go away.
Logcat from crashing Smooth Display:
```
01-03 15:28:19.868  1816  1846 I ActivityManager: Start proc 13858:com.android.refreshratecontrol/u0a280 for restart com.android.refreshratecontrol
01-03 15:28:19.902 13858 13858 I Zygote  : seccomp disabled by setenforce 0
01-03 15:28:19.911 13858 13858 E reshratecontro: Not starting debugger since process cannot load the jdwp agent.
01-03 15:28:19.920  1816  2518 D CompatibilityInfo: mCompatibilityFlags - 4
01-03 15:28:19.920  1816  2518 D CompatibilityInfo: applicationDensity - 420
01-03 15:28:19.920  1816  2518 D CompatibilityInfo: applicationScale - 1.0
01-03 15:28:19.921  1816  2518 D CompatibilityInfo: mCompatibilityFlags - 4
01-03 15:28:19.921  1816  2518 D CompatibilityInfo: applicationDensity - 420
01-03 15:28:19.921  1816  2518 D CompatibilityInfo: applicationScale - 1.0
01-03 15:28:19.935 13858 13858 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.hidl.base-V1.0-java.jar
01-03 15:28:19.935 13858 13858 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.hidl.manager-V1.0-java.jar
01-03 15:28:19.935 13858 13858 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.hidl.base-V1.0-java.jar
01-03 15:28:19.940 13858 13858 W reshratecontro: JIT profile information will not be recorded: profile file does not exits.
01-03 15:28:19.944 13858 13858 I Perf    : Connecting to perf service.
01-03 15:28:19.952 13858 13858 D DisplayModesMonitor: created
01-03 15:28:19.953 13858 13878 E Perf    : Fail to get file list com.android.refreshratecontrol
01-03 15:28:19.953 13858 13878 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
01-03 15:28:19.953 13858 13878 E Perf    : Fail to get file list com.android.refreshratecontrol
01-03 15:28:19.954 13858 13878 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
01-03 15:28:19.955 13858 13858 I DisplayModesMonitor: Ready to configure kernel idle timer. Idle mode id is 0
01-03 15:28:19.955 13858 13858 D AndroidRuntime: Shutting down VM
01-03 15:28:19.956 13858 13858 E AndroidRuntime: FATAL EXCEPTION: main
01-03 15:28:19.956 13858 13858 E AndroidRuntime: Process: com.android.refreshratecontrol, PID: 13858
01-03 15:28:19.956 13858 13858 E AndroidRuntime: java.lang.NoSuchMethodError: No direct method <init>(Landroid/os/Looper;II)V in class Landroid/view/DisplayEventReceiver; or its super classes (declaration of 'android.view.DisplayEventReceiver' appears in /system/framework/framework.jar!classes3.dex)
01-03 15:28:19.956 13858 13858 E AndroidRuntime: 	at com.android.refreshratecontrol.DisplayService$RefreshRateEventReceiver.<init>(DisplayService.java:270)
01-03 15:28:19.956 13858 13858 E AndroidRuntime: 	at com.android.refreshratecontrol.DisplayService.retryPrepareMonitor(DisplayService.java:141)
01-03 15:28:19.956 13858 13858 E AndroidRuntime: 	at com.android.refreshratecontrol.DisplayService.lambda$onCreate$0$DisplayService(DisplayService.java:71)
01-03 15:28:19.956 13858 13858 E AndroidRuntime: 	at com.android.refreshratecontrol.-$$Lambda$DisplayService$wQSMJrm15sQKTFbJgL2c1IU2C50.run(Unknown Source:2)
01-03 15:28:19.956 13858 13858 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
01-03 15:28:19.956 13858 13858 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-03 15:28:19.956 13858 13858 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:359)
01-03 15:28:19.956 13858 13858 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7418)
01-03 15:28:19.956 13858 13858 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-03 15:28:19.956 13858 13858 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-03 15:28:19.956 13858 13858 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
01-03 15:28:19.958  1816 10216 D ActivityManager: New dropbox entry: com.android.refreshratecontrol, system_app_crash, 30b125a7-f5fc-4140-bf45-cb7a3facdc39
01-03 15:28:19.960  1816 10216 W ActivityManager: Process com.android.refreshratecontrol has crashed too many times: killing!
01-03 15:28:19.961  1816 13880 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
01-03 15:28:19.962  1816  1836 I ActivityManager: Showing crash dialog for package com.android.refreshratecontrol u0
```

**Comment by Miustone** [comment]
Hey, looks like the XZ3 Kernel (Or maybe the Panel) has Trouble with the refresh rate Control I've implented. I can't give You a quick fix for that but i will try to solve that with the next Update... If You want to find the fix Yourself, try to check the system.prop from MARS for Lines that contain entries matching to that problem eg:
ro.surface_flinger.refresh_rate_switching=true
ro.surface_flinger.use_content_detection_for_refresh_rate=true
ro.surface_flinger.support_kernel_idle_timer=true

and others. Just change them one by one to false, flash the MARS Zip again and see if it works 👍🏼

**Comment by SimenCodes** [comment]
Update: Flashing the SOM with empty `system.prop` fixes the issue, so definitely something in there. Haven't figured out exactly what (mostly tried `ro.surface_flinger.*` with values from Sony's firmware so far). BTW, using device fingerprint from Pixel 4a 10.0 fixes Pixel launcher's gesture nav, no need for quickswitch.

**Comment by SimenCodes** [comment]
Solved! Remove `vendor.display.disable_inline_rotator=0` and videos play correctly. Dumped my changes in a PR if anyone else is interested. Changed steps compared to Miustone's instructions:
* Download the zip from here instead: https://github.com/SimenCodes/MARS_SOM/tree/h9436-video-fix
* Select Pixel 4a with Android 10 instead of Pixel 5 (this fixes Pixel launcher and 2-button nav)

**Comment by Miustone** [comment]
Thank You very much for the Contribution! 
vendor.display.disable_inline_rotator=0 means that Feature is enabled. It would be great if You could try that Entry with "1" as Value instead of "0". Both Values work on newer Xperias started with the Xperia 2019 Flagships. We can merge it into the Base or i can create a seperated Branch otherwise (Will do that for all (Outdated) Devices who can't run the Base SOM without Issues).
Please keep in Mind that MARS will always aim on newer Devices which are getting the latest Android Releases. As far as i know will the XZ3 not get Android 11 if i'm not wrong. Anyways, if You get Pixel Expierence Android 11 You will be able to run the Base SOM without any changes next. I'm already preparing everything for Android 11 right now. So this Issue can turn out as solved once You run Android 11.

**Comment by SimenCodes** [comment]
The only reason I said to remove the line is that it allows the user's firmware to enable the feature when supported and disable it otherwise. However, feel free to make any changes you think is appropriate.

The XZ3 isn't that old, and there are [good reasons](https://www.independent.co.uk/environment/electronic-waste-recycling-un-report-landfill-phones-minerals-world-economic-forum-davos-a8744371.html) to keep using it. Even though Pixel Experience looks interesting, the XDA thread is unfortunately filled with unresolved reports of stability issues :disappointed:. Sony's Android 11 kernel for Tama devices is released, but the full OS release is not ready yet. Long story short, it would be great if you could keep up Android 10 support for a bit longer (in a separate branch if necessary). :+1:
